local dark_colorscheme = {
    Normal = {bg="#1E1E1E", fg="#DCDCDC"},
    Keyword = {fg="#569CD6"},
    String = {fg="#CE9178"},
    Comment = {fg="#6A9955"},
    Function = {fg="#C586C0"},
    Identifier = {fg="#9CDCFE"},
    Constant = {fg="#B5CEA8"},
    Operator = {fg="#D4D4D4"},
    Delimiter = {fg="#D7BA7D"},
    SignColumn = {bg="#1E1E1E", fg="#DCDCDC"},
    LineNr = {fg="#DCDCDC", bg="#1E1E1E"},
    Cursor = {fg="#1E1E1E", bg="#DCDCDC"},
    CursorLine = {bg="#2B2B2B"},
    Pmenu = {fg="#DCDCDC", bg="#2B2B2B"},
    PmenuSel = {bg="#569CD6", fg="#1E1E1E"},
    StatusLine= {bg="#DCDCDC", fg="#1E1E1E"},
    Search = {bg="#D7BA7D", fg="#1E1E1E"},
    Error = {fg="#FF0000", bg="#1E1E1E"},
    LspDiagnosticsDefaultError = {fg="#FF0000"},
    LspDiagnosticsDefaultWarning = {fg="#FFA500"},
    LspDiagnosticsDefaultInformation = {fg="#1E90FF"},
    LspDiagnosticsDefaultHint = {fg="#00FF00"},
	
    MatchParen = {fg="#FFD700", bg="#44475A", bold=true},
    IncSearch = {fg="#1E1E1E", bg="#FFD700"},
    Folded = {fg="#ABB2BF", bg="#2C323C"},
    NonText = {fg="#ABB2BF"},
    EndOfBuffer = {fg="#1E1E1E"},
    CursorLineNr = {fg="#569CD6", bg="#1E1E1E", bold=true},
    Visual = {bg="#3E4451"},
    SpellBad = {fg="#CE9178", undercurl=true, sp="#AC3000"},
    Whitespace = {fg="#3B4048"},
    Substitute = {fg="#1E1E1E", bg="#C586C0"},
    TODO = {fg="#FFD700", bold=true, italic=true},
    -- Tree-sitter Highlighting
    ["@annotation"] = {fg="#569CD6"},
    ["@attribute"] = {fg="#CE9178"},
    ["@boolean"] = {fg="#569CD6"},
    ["@character"] = {fg="#CE9178"},
    ["@comment"] = {fg="#6A9955"},
    ["@conditional"] = {fg="#C586C0"},
    ["@constant"] = {fg="#9CDCFE"},
    ["@constant.builtin"] = {fg="#9CDCFE"},
    ["@constant.macro"] = {fg="#9CDCFE"},
    ["@constructor"] = {fg="#B5CEA8"},
    ["@error"] = {fg="#FF0000"},
    ["@exception"] = {fg="#C586C0"},
    ["@field"] = {fg="#DCDCDC"},
    ["@float"] = {fg="#D4D4D4"},
    ["@function"] = {fg="#C586C0"},
    ["@function.builtin"] = {fg="#C586C0"},
    ["@function.macro"] = {fg="#C586C0"},
    ["@include"] = {fg="#9CDCFE"},
    ["@keyword"] = {fg="#569CD6"},
    ["@keyword.function"] = {fg="#FFD700"},
    ["@label"] = {fg="#9CDCFE"},
    ["@method"] = {fg="#C586C0"},
    ["@namespace"] = {fg="#9CDCFE"},
    ["@number"] = {fg="#B5CEA8"},
    ["@operator"] = {fg="#D7BA7D"},
    ["@parameter"] = {fg="#9CDCFE"},
    ["@parameter.reference"] = {fg="#9CDCFE"},
    ["@property"] = {fg="#fCDCFE"},
    ["@punctuation.delimiter"] = {fg="#D7BA7D"},
    ["@punctuation.bracket"] = {fg="#D7BA7D"},
    ["@punctuation.special"] = {fg="#D7BA7D"},
    ["@repeat"] = {fg="#569CD6"},
    ["@string"] = {fg="#CE9178"},
    ["@string.regex"] = {fg="#CE9178"},
    ["@string.escape"] = {fg="#CE9178"},
    ["@symbol"] = {fg="#B5CEA8"},
    ["@tag"] = {fg="#569CD6"},
    ["@tag.delimiter"] = {fg="#D7BA7D"},
    ["@text"] = {fg="#DCDCDC"},
    ["@type"] = {fg="#4EC9B0"},
    ["@type.builtin"] = {fg="#4EC9B0"},
    ["@variable"] = {fg="#9CDCFE"},
    ["@variable.builtin"] = {fg="#9CDCFE"},
    -- Add more Tree-sitter highlights as needed
}

return dark_colorscheme
